export default{
    login: require("@/src/assets/auth/login.jpg"),
    googleIcon: require("@/src/assets/icon/icons_google.png"),
    icon1: require("@/src/assets/icon/fluent-mdl2_add-friend.svg"),
    icon2: require("@/src/assets/icon/fluent-mdl2_plan-view.svg"),
    icon3: require("@/src/assets/icon/charm_files.svg"),
    icon4: require("@/src/assets/icon/bi_files.svg"),
    icon5: require("@/src/assets/icon/icon-park-outline_analysis.svg"),
    icon6: require("@/src/assets/icon/wpf_books.svg"),
    icon7: require("@/src/assets/icon/wpf_books.svg"),
    icon8: require("@/src/assets/icon/mdi_rupee.svg"),
    icon9: require("@/src/assets/icon/fa-solid_university.png"),
    icon10: require("@/src/assets/icon/person.svg"),
    elevete_icon: require("@/src/assets/icon/elevete-icon.png"),
    icon11: require("@/src/assets/icon/solar_cup-broken.svg"),
    image2: require("@/src/assets/images/Feedback-rafiki 1.svg"),
    icon12: require("@/src/assets/icon/grommet-icons_plan.svg"),
    email_icon: require("@/src/assets/icon/email-icon.png"),
    image3: require("@/src/assets/images/Certification-pana 1.svg"),
    icon14: require("@/src/assets/icon/calendar_check_icon_136844 1.svg"),
    icon15: require("@/src/assets/icon/simple-line-icons_calender.svg"),
    icon16: require("@/src/assets/images/7386687 1.svg"),
    icon17: require("@/src/assets/images/7386701 1.svg"),
    logo_onetab: require("@/src/assets/images/logo_onetab.png"),
    fee:require("@/src/assets/icon/fee.png"),
    home_img:require("@/src/assets/images/home_oneTab.png")
}